# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement sc of s.

DNA = 'GGTCTTTTGGCCAATGACAACTGAGGGCTCACCCGTTACTGCGGCTGTGACTGGCGATTCTTATGCCCAAGGTTAAATCGCACTGACGGTGGACGCGCAGTCCCATTACGGCCATCTATCGACTCAGCCCTTCTATCTTTTGCCCAACTCTGGCGTGTTTCTAGAGCTATTCCGGGCTAAGTTAAAAAAAGTCTTTGGAGCTATCGTACAGGGGACTGCCGCGGTGATCCGATATGCGAACCAAGTTACTAACCGCATCCGGCCAACGAGCCGCCAACGTTATCACAAAGCGCGCTGTTCTAGTTCGAGTAGCCGGAGACAAGGAAAAGTAGAAACCACACTGCTGACAAATAGCTTTTGTCGGATCGAAGCCGTCCACAGATTCCGGGTATGCACCCCGGGAGCATGGAAGCGGTATGGGAGTAATTGCCACGTGACGAACCCTGACGCCCTTCTATGCCAGCTGCGCGCTCCCACTCTCAACTCCGCTAGTCGTGCTGATAGGAGTCGTCGATTGTAATGCAGGATGCTTACACTTGCGGAATAATATGCCGTGGATAGGGCATTGTACGCTCCCTTAGTGTGAGGGTAACCCCGGCAACCGTCCTTCCTTTGGTAAAGTATTGACAAGTCTAAATAAGAGTTAGCCGATGGCTTTAAGAAGACGATAAACCGGACAACCATACTGCCAGCAGGTGGGCCAACCGCATCTACGGTTTACATTATTTGAGACAGGTTCATAATTTTACCATCGTTACAGGCCGGAAAAGTTCTTACAAAAGCGCATTGCTCTCGGACCCGGAACGGCCAACGCACTGGTAAACCTACTGGACGGT' # I manually pasted the given string by Rosalind.
threeDNA = ''

for n in DNA:
    if n == 'A':
        threeDNA += 'T'
    elif n == 'C':
        threeDNA += 'G'
    elif n == 'G':
        threeDNA += 'C'
    elif n == 'T':
        threeDNA += 'A'
    
DNAcomp = threeDNA[ : :-1]
print(DNAcomp)
    
