DNA = 'GGTCTTTTGGCCAATGACAACTGAGGGCTCACCCGTTACTGCGGCTGTGACTGGCGATTCTTATGCCCAAGGTTAAATCGCACTGACGGTGGACGCGCAGTCCCATTACGGCCATCTATCGACTCAGCCCTTCTATCTTTTGCCCAACTCTGGCGTGTTTCTAGAGCTATTCCGGGCTAAGTTAAAAAAAGTCTTTGGAGCTATCGTACAGGGGACTGCCGCGGTGATCCGATATGCGAACCAAGTTACTAACCGCATCCGGCCAACGAGCCGCCAACGTTATCACAAAGCGCGCTGTTCTAGTTCGAGTAGCCGGAGACAAGGAAAAGTAGAAACCACACTGCTGACAAATAGCTTTTGTCGGATCGAAGCCGTCCACAGATTCCGGGTATGCACCCCGGGAGCATGGAAGCGGTATGGGAGTAATTGCCACGTGACGAACCCTGACGCCCTTCTATGCCAGCTGCGCGCTCCCACTCTCAACTCCGCTAGTCGTGCTGATAGGAGTCGTCGATTGTAATGCAGGATGCTTACACTTGCGGAATAATATGCCGTGGATAGGGCATTGTACGCTCCCTTAGTGTGAGGGTAACCCCGGCAACCGTCCTTCCTTTGGTAAAGTATTGACAAGTCTAAATAAGAGTTAGCCGATGGCTTTAAGAAGACGATAAACCGGACAACCATACTGCCAGCAGGTGGGCCAACCGCATCTACGGTTTACATTATTTGAGACAGGTTCATAATTTTACCATCGTTACAGGCCGGAAAAGTTCTTACAAAAGCGCATTGCTCTCGGACCCGGAACGGCCAACGCACTGGTAAACCTACTGGACGGT'
threeDNA = ''

for n in DNA:
    if n == 'A':
        threeDNA += 'T'
    elif n == 'C':
        threeDNA += 'G'
    elif n == 'G':
        threeDNA += 'C'
    elif n == 'T':
        threeDNA += 'A'
    
DNAcomp = threeDNA[ : :-1]
print(DNAcomp)
    
