# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.


thething = 'GTTCGGCCCTACCTACACAGTACTGACCGTAGCTCGAGGTTATCACCCATTCTATATACGTTTCCCCCGTGGCGAATCATAGTTAATAAAAAAATGGTGAATGCATAGGCTATGAGGGACTGCATCTCATGGATGAGAGTCGCTATGGACGTGCGCGCTAGAACCGGTCAGCCAAGAAATTGGCTAGCATAGTGATTTGCAGCCGACCGTCTGCCCCGGCGCGCGAAAGCTACGTCTCTCTACTCATATTCCCCAGTGCTGAAGGCACGCAGCTGCTAGGTTACTATATTGTCACTATCCTATTTATCAACGCTTAGGCTAAGGGTCACTCAAGTAACCTGGGCACCTTTTCGGGAGGTTCAAACTGGCCCATTTGTGTAAAGGAGGCAGCGTGTTACGTTAGTCTCCAGGCTCGACGTGTACCCCCTTCTCTTCATGCTACGTTCAATGGCAACGACACAACGTGCTGACAGTAGGATCAATATGTAACGTTAGAGGCACTGGCATAGATGACGATGAGCTTAAGCTAGACTCGCCATCATAGCAGCATCGTCAGTACCCAGGAGAGTAAGTACACCCGAACCTGATACCGTCTAGTCCCCAGATTGGCCACGTGCACGACATATCAGTTTCGAGACCACCGATTGTCCCCCTTTTAAACAAGACAGGCCCGAGATCGTTAGTCAAAGCTCGCGAACGAGGTTATGCGGACTAGGGGAATTGCGTTGAAATGTAGAGGACTTCAACTTTAGGGGCCTGCGGCGTACAGGATCCCCAGCAATGTGTCACAACTACTGTGCATTCGATATAGACATAGGCCTGGGATAGTTTTGGAGCGTGACGGGAGTGTGCGGGTTACAA' # for this, I manually inputted the strings that Rosalind provided.

A = 0
G = 0
T = 0
C = 0

for x in thething:
    if x == 'A':
        A = A + 1
    elif x == 'G':
        G = G + 1
    elif x == 'C':
        C = C + 1
    elif x == 'T':
        T = T + 1
print (str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))
