thething = 'GTTCGGCCCTACCTACACAGTACTGACCGTAGCTCGAGGTTATCACCCATTCTATATACGTTTCCCCCGTGGCGAATCATAGTTAATAAAAAAATGGTGAATGCATAGGCTATGAGGGACTGCATCTCATGGATGAGAGTCGCTATGGACGTGCGCGCTAGAACCGGTCAGCCAAGAAATTGGCTAGCATAGTGATTTGCAGCCGACCGTCTGCCCCGGCGCGCGAAAGCTACGTCTCTCTACTCATATTCCCCAGTGCTGAAGGCACGCAGCTGCTAGGTTACTATATTGTCACTATCCTATTTATCAACGCTTAGGCTAAGGGTCACTCAAGTAACCTGGGCACCTTTTCGGGAGGTTCAAACTGGCCCATTTGTGTAAAGGAGGCAGCGTGTTACGTTAGTCTCCAGGCTCGACGTGTACCCCCTTCTCTTCATGCTACGTTCAATGGCAACGACACAACGTGCTGACAGTAGGATCAATATGTAACGTTAGAGGCACTGGCATAGATGACGATGAGCTTAAGCTAGACTCGCCATCATAGCAGCATCGTCAGTACCCAGGAGAGTAAGTACACCCGAACCTGATACCGTCTAGTCCCCAGATTGGCCACGTGCACGACATATCAGTTTCGAGACCACCGATTGTCCCCCTTTTAAACAAGACAGGCCCGAGATCGTTAGTCAAAGCTCGCGAACGAGGTTATGCGGACTAGGGGAATTGCGTTGAAATGTAGAGGACTTCAACTTTAGGGGCCTGCGGCGTACAGGATCCCCAGCAATGTGTCACAACTACTGTGCATTCGATATAGACATAGGCCTGGGATAGTTTTGGAGCGTGACGGGAGTGTGCGGGTTACAA'

A = 0
G = 0
T = 0
C = 0

for x in thething:
    if x == 'A':
        A = A + 1
    elif x == 'G':
        G = G + 1
    elif x == 'C':
        C = C + 1
    elif x == 'T':
        T = T + 1
print (str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))
